// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfvf9hrZb6DDf_aaKFQ0gcQ5pTozUI644',
    appId: '1:68632017979:web:c8c70c793c7a78d5a1f01e',
    messagingSenderId: '68632017979',
    projectId: 'perapal-b92ec',
    authDomain: 'perapal-b92ec.firebaseapp.com',
    storageBucket: 'perapal-b92ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWtvafZckJyh-tUp0M6IU2q3eQG_9JZnA',
    appId: '1:68632017979:android:e45f57fcd343affea1f01e',
    messagingSenderId: '68632017979',
    projectId: 'perapal-b92ec',
    storageBucket: 'perapal-b92ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHCWEpvc1vCVN0PYKi8mP0itZSbkQYU4',
    appId: '1:68632017979:ios:d1fda9c19c31de86a1f01e',
    messagingSenderId: '68632017979',
    projectId: 'perapal-b92ec',
    storageBucket: 'perapal-b92ec.appspot.com',
    iosClientId: '68632017979-lec26nr6qnf74epldli4j4k6antgi5vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.perapal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHCWEpvc1vCVN0PYKi8mP0itZSbkQYU4',
    appId: '1:68632017979:ios:d1fda9c19c31de86a1f01e',
    messagingSenderId: '68632017979',
    projectId: 'perapal-b92ec',
    storageBucket: 'perapal-b92ec.appspot.com',
    iosClientId: '68632017979-lec26nr6qnf74epldli4j4k6antgi5vn.apps.googleusercontent.com',
    iosBundleId: 'com.example.perapal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfvf9hrZb6DDf_aaKFQ0gcQ5pTozUI644',
    appId: '1:68632017979:web:f394eb14bd6d4391a1f01e',
    messagingSenderId: '68632017979',
    projectId: 'perapal-b92ec',
    authDomain: 'perapal-b92ec.firebaseapp.com',
    storageBucket: 'perapal-b92ec.appspot.com',
  );
}
